import { Mode } from '@/components/chat/ChatInput';

export const SUGGESTION_POOL: { text: string; mode: Mode }[] = [
    // --- Clinical Pharmacology & Therapeutics ---
    { text: 'What are the common drug interactions with Warfarin?', mode: 'detailed' },
    { text: 'Explain the mechanism of action of SSRIs', mode: 'detailed' },
    { text: 'Compare ACE inhibitors vs ARBs in treating hypertension', mode: 'detailed' },
    { text: 'List potential side effects of GLP-1 agonists', mode: 'detailed' },
    { text: 'Analyze the structure-activity relationship of beta-lactams', mode: 'detailed' },
    { text: 'What are the contraindications for tissue plasminogen activator (tPA)?', mode: 'detailed' },
    { text: 'Discuss the pharmacokinetics of therapeutic monoclonal antibodies', mode: 'detailed' },
    { text: 'Explain the CYP450 enzyme inhibition profile of ritonavir', mode: 'detailed' },
    { text: 'What are the current treatment guidelines for H. pylori infection?', mode: 'detailed' },
    { text: 'Describe the mechanism of resistance to vancomycin in S. aureus', mode: 'detailed' },
    { text: 'Review the cardiac safety profile of hydroxychloroquine', mode: 'detailed' },
    { text: 'What are the monitoring requirements for clozapine therapy?', mode: 'detailed' },
    { text: 'Explain the difference between first and second-generation antipsychotics', mode: 'detailed' },
    { text: 'Discuss the role of SGLT2 inhibitors in heart failure management', mode: 'detailed' },
    { text: 'What is the antidote for acetaminophen toxicity and how does it work?', mode: 'detailed' },
    { text: 'Compare the efficacy of direct oral anticoagulants (DOACs) vs Warfarin', mode: 'detailed' },
    { text: 'Explain the "cheese effect" associated with MAO inhibitors', mode: 'detailed' },
    { text: 'What are the risk factors for statin-induced myopathy?', mode: 'detailed' },
    { text: 'Describe the pharmacodynamics of neuromuscular blocking agents', mode: 'detailed' },
    { text: 'What are the red flag signs of Stevens-Johnson Syndrome?', mode: 'detailed' },
    { text: 'Explain the rationale for beta-blockers in thyrotoxicosis management', mode: 'detailed' },
    { text: 'List drugs known to prolong the QT interval', mode: 'detailed' },
    { text: 'Discuss the management of heparin-induced thrombocytopenia (HIT)', mode: 'detailed' },
    { text: 'What are the indications for prophylactic antibiotic in surgery?', mode: 'detailed' },
    { text: 'Explain the mechanism of action of checkpoint inhibitors in oncology', mode: 'detailed' },
    { text: 'Compare the bioavailability of intravenous vs oral ciprofloxacin', mode: 'detailed' },
    { text: 'What are the adverse effects of long-term corticosteroid use?', mode: 'detailed' },
    { text: 'Discuss the impact of renal impairment on digoxin dosing', mode: 'detailed' },
    { text: 'Explain the concept of enterohepatic circulation of drugs', mode: 'detailed' },
    { text: 'What are the treatment options for multidrug-resistant tuberculosis?', mode: 'detailed' },
    { text: 'Describe the mechanism of action of proton pump inhibitors (PPIs)', mode: 'detailed' },
    { text: 'What is the role of naloxone in opioid overdose management?', mode: 'detailed' },
    { text: 'Compare the onset of action of rapid-acting vs long-acting insulins', mode: 'detailed' },
    { text: 'Explain the significance of protein binding in drug distribution', mode: 'detailed' },
    { text: 'What are the clinical signs of digoxin toxicity?', mode: 'detailed' },
    { text: 'Discuss the use of bisphosphonates in osteoporosis treatment', mode: 'detailed' },
    { text: 'What are the common adverse events associated with chemotherapy?', mode: 'detailed' },
    { text: 'Explain the mechanism of action of local anesthetics', mode: 'detailed' },
    { text: 'Compare the pharmacology of benzodiazepines vs Z-drugs', mode: 'detailed' },
    { text: 'What are the therapeutic guidelines for community-acquired pneumonia?', mode: 'detailed' },
    { text: 'Discuss the role of anticholinergics in COPD management', mode: 'detailed' },
    { text: 'Explain the "first-pass effect" and its clinical relevance', mode: 'detailed' },
    { text: 'What are the differences between COX-1 and COX-2 inhibitors?', mode: 'detailed' },
    { text: 'Describe the pharmacokinetics of lithium in bipolar disorder', mode: 'detailed' },
    { text: 'What are the treatment protocols for anaphylactic shock?', mode: 'detailed' },
    { text: 'Compare the efficacy of different classes of diuretics', mode: 'detailed' },
    { text: 'Explain the mechanism of action of antiviral drugs for HIV', mode: 'detailed' },
    { text: 'What are the potential interactions between herbal supplements and prescribed meds?', mode: 'detailed' },
    { text: 'Discuss the management of febrile neutropenia in cancer patients', mode: 'detailed' },
    { text: 'Explain the role of thrombolytics in acute ischemic stroke', mode: 'detailed' },

    // --- Research, Writing & Academic ---
    { text: 'Help me write a research manuscript introduction', mode: 'detailed' },
    { text: 'Draft an abstract for a study on mRNA vaccine stability', mode: 'detailed' },
    { text: 'Write a literature review on antibiotic resistance mechanisms', mode: 'detailed' },
    { text: 'Suggest a title for a paper on AI in drug discovery', mode: 'detailed' },
    { text: 'Outline the structure of a Phase I clinical trial protocol', mode: 'detailed' },
    { text: 'Help me summarize this clinical study result', mode: 'detailed' },
    { text: 'Generate keywords for a systematic review on hypertension', mode: 'detailed' },
    { text: 'Write a conclusion paragraph for a case study on rare adverse events', mode: 'detailed' },
    { text: 'Create an outline for a review article on CRISPR therapeutics', mode: 'detailed' },
    { text: 'Check this paragraph for clarity and academic tone', mode: 'detailed' },
    { text: 'Suggest statistical methods for analyzing survival data', mode: 'detailed' },
    { text: 'Write a cover letter for a submission to a pharmacology journal', mode: 'detailed' },
    { text: 'Summarize the key findings of the attached PDF', mode: 'detailed' },
    { text: 'Formulate a hypothesis for a study on microbiome-drug interactions', mode: 'detailed' },
    { text: 'Draft a methodology section for a retrospective cohort study', mode: 'detailed' },
    { text: 'Create a table legend for demographic data distribution', mode: 'detailed' },
    { text: 'Write a plain language summary for a complex PK/PD study', mode: 'detailed' },
    { text: 'Suggest relevant journals for a paper on pediatric dosing', mode: 'detailed' },
    { text: 'Help me rephrase this discussion section to be more concise', mode: 'detailed' },
    { text: 'Identify potential bias in this study design', mode: 'detailed' },
    { text: 'Draft an email to a collaborator about sharing research data', mode: 'detailed' },
    { text: 'Write a limitation section for a cross-sectional survey study', mode: 'detailed' },
    { text: 'Suggest figure ideas to visualize drug release kinetics', mode: 'detailed' },
    { text: 'Help me write an acknowledgement section for grant funding', mode: 'detailed' },
    { text: 'Outline a grant proposal for a novel antimicrobial target', mode: 'detailed' },

    // --- Regulatory Affairs & Industry ---
    { text: 'Summarize the latest FDA guidelines for biosimilars', mode: 'detailed' },
    { text: 'What are phase III trial requirements for orphan drugs?', mode: 'detailed' },
    { text: 'Explain the Fast Track designation process by the FDA', mode: 'detailed' },
    { text: 'What are the reporting requirements for adverse events (post-market)?', mode: 'detailed' },
    { text: 'Compare FDA vs EMA approval processes for new molecular entities', mode: 'detailed' },
    { text: 'What is a 505(b)(2) NDA pathway?', mode: 'detailed' },
    { text: 'Explain the importance of Good Manufacturing Practice (GMP)', mode: 'detailed' },
    { text: 'What are the labeling requirements for pregnancy warnings?', mode: 'detailed' },
    { text: 'Discuss the concept of Real-World Evidence (RWE) in regulatory decisions', mode: 'detailed' },
    { text: 'What is an Investigational New Drug (IND) application?', mode: 'detailed' },
    { text: 'Explain the Priority Review Voucher program', mode: 'detailed' },
    { text: 'What are the differences between a generic drug and a biosimilar?', mode: 'detailed' },
    { text: 'Describe the role of the DSMB in clinical trials', mode: 'detailed' },
    { text: 'What is the "Black Box Warning" and when is it issued?', mode: 'detailed' },
    { text: 'Explain the requirements for electronic Common Technical Document (eCTD)', mode: 'detailed' },
    { text: 'What are the guidelines for conducting pediatric clinical trials?', mode: 'detailed' },
    { text: 'Discuss the regulatory landscape for digital therapeutics', mode: 'detailed' },
    { text: 'What is the Orphan Drug Act and its incentives?', mode: 'detailed' },
    { text: 'Explain the regulation of dietary supplements vs drugs', mode: 'detailed' },
    { text: 'What are the key elements of an Informed Consent Form (ICF)?', mode: 'detailed' },
    { text: 'Describe the pharmacovigilance responsibilities of a permit holder', mode: 'detailed' },
    { text: 'What is a Risk Evaluation and Mitigation Strategy (REMS)?', mode: 'detailed' },
    { text: 'Explain the changes in the EU Clinical Trials Regulation (CTR)', mode: 'detailed' },
    { text: 'What is the role of ICH guidelines in global drug development?', mode: 'detailed' },
    { text: 'Discuss the patent exclusivity period for biologics', mode: 'detailed' },

    // --- Deep Research Queries ---
    { text: 'Deep research: Current evidence for pembrolizumab in NSCLC', mode: 'deep_research' },
    { text: 'Deep research: Emerging CAR-T therapies for solid tumors', mode: 'deep_research' },
    { text: 'Deep research: Long-term outcomes of gene therapy in hemophilia', mode: 'deep_research' },
    { text: 'Deep research: AI applications in drug discovery 2024', mode: 'deep_research' },
    { text: 'Deep research: Mechanisms of resistance to EGFR tyrosine kinase inhibitors', mode: 'deep_research' },
    { text: 'Deep research: Potential of exosomes as drug delivery systems', mode: 'deep_research' },
    { text: 'Deep research: Role of gut microbiome in immunotherapy response', mode: 'deep_research' },
    { text: 'Deep research: Advances in treating Alzheimer\'s disease via amyloid targeting', mode: 'deep_research' },
    { text: 'Deep research: Safety efficacy of mRNA vaccines beyond COVID-19', mode: 'deep_research' },
    { text: 'Deep research: Targeting KRAS mutations in pancreatic cancer', mode: 'deep_research' },
    { text: 'Deep research: Novel anticoagulants for patients with renal failure', mode: 'deep_research' },
    { text: 'Deep research: Epigenetic modifications in drug resistance', mode: 'deep_research' },
    { text: 'Deep research: Advances in antibody-drug conjugates (ADCs) for breast cancer', mode: 'deep_research' },
    { text: 'Deep research: Comparative analysis of GLP-1 and GIP receptor agonists', mode: 'deep_research' },
    { text: 'Deep research: Therapeutic potential of CRISPR/Cas9 in sickle cell disease', mode: 'deep_research' },
    { text: 'Deep research: Impact of pharmacogenomics on warfarin dosing algorithms', mode: 'deep_research' },
    { text: 'Deep research: Emerging treatments for non-alcoholic steatohepatitis (NASH)', mode: 'deep_research' },
    { text: 'Deep research: Biomarkers for predicting response to checkpoint inhibitors', mode: 'deep_research' },
    { text: 'Deep research: Nanotechnology applications in targeted cancer therapy', mode: 'deep_research' },
    { text: 'Deep research: The role of inflammation in depression and novel anti-inflammatory antidepressants', mode: 'deep_research' },
    { text: 'Deep research: Repurposing metformin for anti-aging and longevity', mode: 'deep_research' },
    { text: 'Deep research: Efficacy of psilocybin-assisted therapy for treatment-resistant depression', mode: 'deep_research' },
    { text: 'Deep research: Advances in 3D bioprinting for drug testing models', mode: 'deep_research' },
    { text: 'Deep research: Current status of male contraceptive drug development', mode: 'deep_research' },
    { text: 'Deep research: Gene editing strategies for HIV cure', mode: 'deep_research' },

    // --- Drug Discovery & Development ---
    { text: 'Explain the concept of "hit-to-lead" optimization', mode: 'detailed' },
    { text: 'What are the advantages of fragment-based drug design?', mode: 'detailed' },
    { text: 'Discuss the role of high-throughput screening in modern discovery', mode: 'detailed' },
    { text: 'What is Lipinski\'s Rule of Five?', mode: 'detailed' },
    { text: 'Explain the difference between small molecules and biologics production', mode: 'detailed' },
    { text: 'What are PROTACs and how do they work?', mode: 'detailed' },
    { text: 'Discuss the challenges of delivering drugs across the blood-brain barrier', mode: 'detailed' },
    { text: 'What is molecular docking and how is it used?', mode: 'detailed' },
    { text: 'Explain the significance of bioisosteres in medicinal chemistry', mode: 'detailed' },
    { text: 'What are the ethical considerations in animal testing for new drugs?', mode: 'detailed' },
    { text: 'Describe the process of lead optimization', mode: 'detailed' },
    { text: 'What is phenotypic screening vs target-based screening?', mode: 'detailed' },
    { text: 'Explain the importance of solubility and permeability in drug formulation', mode: 'detailed' },
    { text: 'What are the current trends in peptide therapeutics?', mode: 'detailed' },
    { text: 'Discuss the potential of RNA interaction as a therapeutic target', mode: 'detailed' },
    { text: 'What is scaffold hopping in drug design?', mode: 'detailed' },
    { text: 'Explain the concept of polypharmacology', mode: 'detailed' },
    { text: 'What are cell-penetrating peptides?', mode: 'detailed' },
    { text: 'Discuss the role of computational toxicity prediction', mode: 'detailed' },
    { text: 'What is the difference between pharmacokinetic and pharmacodynamic optimization?', mode: 'detailed' },
    { text: 'Explain the use of biomarkers in early clinical development', mode: 'detailed' },
    { text: 'What are the challenges in developing drugs for rare diseases?', mode: 'detailed' },
    { text: 'Discuss the future of personalized medicine in drug development', mode: 'detailed' },
    { text: 'What is drug repurposing and give an example?', mode: 'detailed' },
    { text: 'Explain the role of ADME/Tox studies in preclinical development', mode: 'detailed' },

    // --- Miscellaneous & specific scenarios ---
    { text: 'Calculate the creatinine clearance for a 75-year-old male', mode: 'detailed' },
    { text: 'Interpret these ABG results: pH 7.25, pCO2 60, HCO3 26', mode: 'detailed' },
    { text: 'What counseling points should be given for inhaler technique?', mode: 'detailed' },
    { text: 'Explain the difference between bacteriostatic and bactericidal antibiotics', mode: 'detailed' },
    { text: 'What is the dosing regimen for post-exposure prophylaxis (PEP) for HIV?', mode: 'detailed' },
    { text: 'Discuss the management of status epilepticus in the ER', mode: 'detailed' },
    { text: 'What are the alternatives to epinephrine in cardiac arrest?', mode: 'detailed' },
    { text: 'Explain the mechanism of action of botulinum toxin', mode: 'detailed' },
    { text: 'What are the signs of opioid withdrawal?', mode: 'detailed' },
    { text: 'Discuss the treatment approach for hyperkalemia', mode: 'detailed' },
    { text: 'What is the mechanism of action of metformin?', mode: 'detailed' },
    { text: 'Explain the pathophysiology of asthma', mode: 'detailed' },
    { text: 'What are the common causes of medication errors in hospitals?', mode: 'detailed' },
    { text: 'Discuss the role of the pharmacist in antimicrobial stewardship', mode: 'detailed' },
    { text: 'What is the Beers Criteria for older adults?', mode: 'detailed' },
    { text: 'Explain the concept of therapeutic index', mode: 'detailed' },
    { text: 'What are the interactions between grapefruit juice and statins?', mode: 'detailed' },
    { text: 'Discuss the mechanism of action of cannabis-based medicines', mode: 'detailed' },
    { text: 'What is the role of vitamins in preventive medicine?', mode: 'detailed' },
    { text: 'Explain the difference between Type 1 and Type 2 drug allergies', mode: 'detailed' },
    { text: 'What are the storage requirements for mRNA vaccines?', mode: 'detailed' },
    { text: 'Discuss the ethical implications of genetic testing', mode: 'detailed' },
    { text: 'What is the difference between a side effect and an adverse drug reaction?', mode: 'detailed' },
    { text: 'Explain the mechanism of action of aspirin as an antiplatelet', mode: 'detailed' },
    { text: 'What are the guidelines for handling hazardous drugs (USP 800)?', mode: 'detailed' },
];
