[global]
# Development mode settings
developmentMode = false
showWarningOnDirectExecution = false

[server]
# Server configuration for Streamlit Cloud
headless = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

# Port configuration (Streamlit Cloud handles this automatically)
port = 8501

[browser]
# Browser settings
gatherUsageStats = false

[theme]
# Kiro-inspired purplish theme
base = "dark"
primaryColor = "#8B5CF6"          # Purple primary (violet-500)
backgroundColor = "#0F0F23"        # Deep dark blue-purple background
secondaryBackgroundColor = "#1E1B3A"  # Slightly lighter purple-dark
textColor = "#E5E7EB"             # Light gray text


[runner]
# Runner configuration for better performance
magicEnabled = true