[global]
# Development mode settings
developmentMode = false
showWarningOnDirectExecution = false

[server]
# Server configuration for Streamlit Cloud
headless = true
enableXsrfProtection = true
maxUploadSize = 20
maxMessageSize = 200

# Port configuration (Streamlit Cloud handles this automatically)
port = 8501

[browser]
# Browser settings
gatherUsageStats = false

[theme]
# Normal dark theme
base = "dark"


[runner]
# Runner configuration for better performance
magicEnabled = true